site_config: .site-config.yml
brand_name: $program_name
brand_path: ../$brand_name
image_path: $brand_link/images
landing:
  page: /index
  path: /home
  content: $path
authenticated:
  page: /index
  path: /home
  content: $path
log_dir: ../log
log_file: $brand_name.log
upload_dir: ../uploads
css:
  - /common/didi.css
scripts:
  - /jquery-min.js
  - /jquery-ui.min.js
  - /common/mukoni.jquery.js
  - /common/mkn.js
  - /common/mkn.render.js
  - /common/page.js
helpers:
  - collection
  - emailer

search_paths: [../common/,.,$brand_path]
collections:
  default: collection
  session: [session,audit]
  auth: [user,partner,role]

registrar_role: registrar
email_new_registration: yes

email_otp: yes
sms_otp: yes
request_method: post
smtp_host: smtp.example.com
smtp_user: email@example.com
smtp_password: mypassword
send_sms:
  protocol: http
  port: 80
  host: www.qmessenger.co.za
  user: minime
  password: mypassword
  path: web2sms/submit?uid=$user&pw=$password&sms=$message&da=$cellphone
emailer.send:
  smtp:
    host: smtp.example.com
    user: me@example.com
    password: mypassword
