site_config: .site-config.yml
brand_name: $program_name
brand_path: ../$brand_name
landing:
  page: /index
authenticated:
  page: /index
  path: /home
  content: $path
start_page: home
log_dir: ../log
log_file: $brand_name.log
upload_dir: ../uploads
css:
  - /common/didi.css
  - /.$brand_name/brand.css
scripts:
  - /jquery-min.js
  - /jquery-ui.min.js
  - /common/mukoni.jquery.js
  - /common/mkn.js
  - /common/mkn.render.js
  - /common/page.js
helpers:
  - collection

email_otp: yes
sms_otp: yes
request_method: post
smtp_host: smtp.example.com
smtp_user: email@example.com
smtp_password: mypassword
send_sms:
  protocol: http
  port: 80
  host: www.qmessenger.co.za
  user: minime
  password: mypassword
  path: web2sms/submit?uid=$user&pw=$password&sms=$message&da=$cellphone
send_email:
  host: smtp.example.com
  user: me@example.com
  password: mypassword
